# Include the required scripts for the bacterial model

include("abm_bacterial.jl")
include("bact_agent_step.jl")
include("bact_model_step.jl")
include("bacterial_population.jl")
include("bacterial_treatment.jl")
include("bact_infection.jl")
include("bact_fitness.jl")
include("bact_plasmid_transfer.jl")
include("bact_empty_neighbours.jl")
include("bact_treatment_response.jl")
include("export_bacterial_position.jl")
include("export_bacterial_data.jl")
include("bact_invasion.jl")
include("bact_recovery.jl")
include("bact_carrier_state.jl")
include("bact_stressor.jl")
include("bact_infected_transition.jl")
include("thread_submodel.jl")
include("bact_export_headers.jl")
include("abm_bact_submodel.jl")